Cargo.lock, Cargo.toml, src/contract.rs, src/helpers.rs, src/lib.rs, src/types/error.rs, src/types/msg.rs
closes: https://github.com/srdtrk/cw-ica-controller/issues/9
=> feat: added `helpers.rs` and basic migration logic

.github/workflows/Release.yml
This PR also gives it the ability to be triggered manually
=> ci: re-run 'Release.yml' on release edits

Cargo.lock, Cargo.toml, src/contract.rs, src/helpers.rs, src/ibc/relay.rs, src/ibc/types/packet.rs, src/types/callbacks.rs, src/types/state.rs, testing/contracts/cw-ica-owner/Cargo.lock
This still keeps cosmwasm 1.2 compatibility.
=> deps: bump cosmwasm to 1.5

Cargo.toml, src/ibc/mod.rs, src/lib.rs, testing/contracts/cw-ica-owner/Cargo.toml
=> imp: removed library feature

.github/workflows/e2e.yml, Cargo.toml, README.md, testing/contracts/cw-ica-owner/Cargo.toml
CosmWasm combined the rust-optimizer and workspace-optimizer into `cosmwasm/optimizer`
=> deps: promote rust-optimizer to 0.15

.github/workflows/e2e.yml, Cargo.lock, Cargo.toml, e2e/interchaintest/chain_config.go, src/contract.rs, src/helpers.rs, src/ibc/handshake.rs, src/ibc/relay.rs, src/ibc/types/events.rs, src/ibc/types/keys.rs, src/ibc/types/metadata.rs, src/ibc/types/packet.rs, src/ibc/types/stargate.rs, src/lib.rs, src/types/callbacks.rs, src/types/cosmos_msg.rs, src/types/error.rs, src/types/keys.rs, src/types/mod.rs, src/types/msg.rs, src/types/state.rs, testing/contracts/cw-ica-owner/Cargo.lock, testing/contracts/cw-ica-owner/src/contract.rs
This PR:
- enforces clippy::pedantic, clippy::nursery, warnings
- bumps wasmd to 0.45.0
- adds deps cache to ci for interchaintest
=> style!: enforcing clippy::pedantic and clippy::nursery

.github/workflows/e2e.yml, Cargo.lock, Cargo.toml, README.md, e2e/interchaintest/contract_test.go, e2e/interchaintest/owner_test.go, e2e/interchaintest/types/ica_contract.go, e2e/interchaintest/types/ica_query.go, e2e/interchaintest/types/ica_state.go, src/contract.rs, src/ibc/handshake.rs, src/ibc/relay.rs, src/ibc/types/metadata.rs, src/types/error.rs, src/types/msg.rs, src/types/state.rs, testing/contracts/cw-ica-owner/Cargo.lock, testing/contracts/cw-ica-owner/src/contract.rs
=> imp: use cw-ownable to manage owner

Cargo.toml, e2e/interchaintest/contract_test.go, e2e/interchaintest/testsuite/grpc_query.go, e2e/interchaintest/types/cosmos_msg.go, e2e/interchaintest/types/ica_contract.go, e2e/interchaintest/types/ica_msg.go, src/contract.rs, src/ibc/types/packet.rs, src/types/cosmos_msg.rs, src/types/msg.rs
=> feat: add CosmosMsg support

e2e/interchaintest/contract_test.go, e2e/interchaintest/go.mod, e2e/interchaintest/types/ica_contract.go, e2e/interchaintest/types/ica_msg.go, src/contract.rs, src/ibc/handshake.rs, src/ibc/types/metadata.rs, src/ibc/types/stargate.rs, src/types/error.rs, src/types/msg.rs, src/types/state.rs
=> imp: remove stargate query

README.md
=> docs: added badges to readme

.github/workflows/e2e.yml, .github/workflows/rust.yml, README.md
This PR;
- removed the blue lines under the badges
- improves the language of readme
- ci doesn't run if only `.md` files are changed
=> docs: improve readme and ci

README.md
=> docs: added demo to readme

e2e/interchaintest/contract_test.go, e2e/interchaintest/testsuite/grpc_query.go, e2e/interchaintest/wasm_msg_test.go
Slightly removed grpc querier boilerplate
=> imp(e2e): refactored grpc querier

Cargo.lock, Cargo.toml, README.md, e2e/interchaintest/contract_test.go, e2e/interchaintest/owner_test.go, e2e/interchaintest/types/icacontroller/msg.go, e2e/interchaintest/types/owner/msg.go, e2e/interchaintest/wasm_msg_test.go, src/contract.rs, src/ibc/types/stargate.rs, src/types/msg.rs, src/types/state.rs, testing/contracts/callback-counter/src/contract.rs, testing/contracts/cw-ica-owner/src/contract.rs, testing/contracts/cw-ica-owner/src/msg.rs
=> imp!: enforce channel open init on instantiate

CHANGELOG.md
=> docs: updated changelog for v0.4.0

CHANGELOG.md, Cargo.lock, src/helpers.rs, testing/contracts/cw-ica-owner/Cargo.lock, testing/contracts/cw-ica-owner/src/contract.rs
=> imp!: `instantiate2` helper function now returns address

CHANGELOG.md, Cargo.lock, Cargo.toml, derive/Cargo.toml, derive/src/lib.rs, testing/contracts/callback-counter/Cargo.lock, testing/contracts/callback-counter/src/msg.rs, testing/contracts/cw-ica-owner/Cargo.lock
=> imp: added inline comments to the enum variant inserted by proc macro

Cargo.lock, e2e/interchaintest/contract_test.go, e2e/interchaintest/owner_test.go, e2e/interchaintest/types/icacontroller/types.go, src/contract.rs, src/helpers.rs, src/ibc/handshake.rs, src/types/state.rs, testing/contracts/callback-counter/Cargo.lock, testing/contracts/cw-ica-owner/Cargo.lock, testing/contracts/cw-ica-owner/src/contract.rs
=> imp!: improve public API

e2e/interchaintest/contract_test.go, e2e/interchaintest/testsuite/constants.go, e2e/interchaintest/testsuite/suite.go, e2e/interchaintest/types/icacontroller/msg.go, src/contract.rs, src/ibc/handshake.rs, src/types/error.rs, src/types/msg.rs, src/types/state.rs
=> imp: added CloseChannel

README.md, docs/docs/contract-api/02-execute-msg.mdx, docs/docs/contract-api/03-query-msg.mdx
=> docs: add close channel docs and update 'README.md'

.github/workflows/e2e.yml, e2e/Readme.md, e2e/interchaintest/contract_test.go
=> imp(e2e): add close channel test for unordered channel

.github/workflows/e2e.yml, Cargo.lock, Cargo.toml, testing/Readme.md, testing/contracts/callback-counter/Cargo.lock, testing/contracts/callback-counter/Cargo.toml, testing/contracts/cw-ica-owner/Cargo.lock, testing/contracts/cw-ica-owner/Cargo.toml
=> deps: removed support for cosmwasm v1.3

e2e/interchaintestv8/contract_test.go, e2e/interchaintestv8/types/callbackcounter/msgs.go, e2e/interchaintestv8/wasm_msg_test.go, testing/contracts/callback-counter/src/contract.rs, testing/contracts/callback-counter/src/state.rs
=> imp(testing/callback-counter): entire callback msgs are stored

justfile
=> imp: added generate-schemas to justfile

CHANGELOG.md, Cargo.lock, src/helpers.rs, src/ibc/types/metadata.rs, src/types/state.rs, testing/contracts/callback-counter/Cargo.lock, testing/contracts/cw-ica-owner/Cargo.lock, testing/contracts/cw-ica-owner/src/contract.rs
=> imp!: improve helpers

.github/workflows/e2e.yml, .github/workflows/rust.yml
=> revert: 'ci: condition 'e2e.yml' on 'rust.yml' (#120)'

.github/workflows/e2e.yml, e2e/interchaintestv8/e2esuite/diagnostics.go, e2e/interchaintestv8/wasm_msg_test.go
=> fix(e2e): diagnostics uploads
